include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - 'lib/protobuf/**.dart'
    - 'rust/bridge/ffi/**.dart'

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
linter:
  rules:
    avoid_print: false
    avoid_redundant_argument_values: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unnecessary_await_in_return: true
    unnecessary_parenthesis: true
