[workspace]
resolver = "1"
members = [
    "packages/agent_dart_ffi/native/agent_dart",
    "packages/agent_dart_ffi/native/ed_compact",
]
exclude = [
    "packages/agent_dart/native",
    "packages/agent_dart_base/native",
]

[profile.release]
debug = false
lto = true
opt-level = "z"
