[package]
name = "ed_compact"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["random", "std"]
pem = ["ct-codecs"]
random = ["getrandom"]
traits = ["ed25519"]
self-verify = []
blind-keys = []
std = []
opt_size = []

[dependencies]
ct-codecs = { version = "1.1.5", optional = true }
getrandom = { version = "0.3.3", optional = true }
ed25519 = { version = "1.5.3", optional = true }

[dev-dependencies]
getrandom = "0.3.3"
ct-codecs = "1.1.5"
