// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.72.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, unnecessary_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member, prefer_is_empty, unnecessary_const

import 'dart:convert';
import 'dart:async';
import 'package:meta/meta.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'bridge_generated.dart';
export 'bridge_generated.dart';
import 'dart:ffi' as ffi;

class AgentDartPlatform extends FlutterRustBridgeBase<AgentDartWire> {
  AgentDartPlatform(ffi.DynamicLibrary dylib) : super(AgentDartWire(dylib));

// Section: api2wire

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_String(String raw) {
    return api2wire_uint_8_list(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_AesDecryptReq> api2wire_box_autoadd_aes_decrypt_req(AesDecryptReq raw) {
    final ptr = inner.new_box_autoadd_aes_decrypt_req_0();
    _api_fill_to_wire_aes_decrypt_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_AesEncryptReq> api2wire_box_autoadd_aes_encrypt_req(AesEncryptReq raw) {
    final ptr = inner.new_box_autoadd_aes_encrypt_req_0();
    _api_fill_to_wire_aes_encrypt_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_BLSVerifyReq> api2wire_box_autoadd_bls_verify_req(BLSVerifyReq raw) {
    final ptr = inner.new_box_autoadd_bls_verify_req_0();
    _api_fill_to_wire_bls_verify_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_ED25519FromSeedReq> api2wire_box_autoadd_ed_25519_from_seed_req(ED25519FromSeedReq raw) {
    final ptr = inner.new_box_autoadd_ed_25519_from_seed_req_0();
    _api_fill_to_wire_ed_25519_from_seed_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_ED25519SignReq> api2wire_box_autoadd_ed_25519_sign_req(ED25519SignReq raw) {
    final ptr = inner.new_box_autoadd_ed_25519_sign_req_0();
    _api_fill_to_wire_ed_25519_sign_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_ED25519VerifyReq> api2wire_box_autoadd_ed_25519_verify_req(ED25519VerifyReq raw) {
    final ptr = inner.new_box_autoadd_ed_25519_verify_req_0();
    _api_fill_to_wire_ed_25519_verify_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_P256FromSeedReq> api2wire_box_autoadd_p_256_from_seed_req(P256FromSeedReq raw) {
    final ptr = inner.new_box_autoadd_p_256_from_seed_req_0();
    _api_fill_to_wire_p_256_from_seed_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_P256ShareSecretReq> api2wire_box_autoadd_p_256_share_secret_req(P256ShareSecretReq raw) {
    final ptr = inner.new_box_autoadd_p_256_share_secret_req_0();
    _api_fill_to_wire_p_256_share_secret_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_P256SignWithSeedReq> api2wire_box_autoadd_p_256_sign_with_seed_req(P256SignWithSeedReq raw) {
    final ptr = inner.new_box_autoadd_p_256_sign_with_seed_req_0();
    _api_fill_to_wire_p_256_sign_with_seed_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_P256VerifyReq> api2wire_box_autoadd_p_256_verify_req(P256VerifyReq raw) {
    final ptr = inner.new_box_autoadd_p_256_verify_req_0();
    _api_fill_to_wire_p_256_verify_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_PBKDFDeriveReq> api2wire_box_autoadd_pbkdf_derive_req(PBKDFDeriveReq raw) {
    final ptr = inner.new_box_autoadd_pbkdf_derive_req_0();
    _api_fill_to_wire_pbkdf_derive_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_PhraseToSeedReq> api2wire_box_autoadd_phrase_to_seed_req(PhraseToSeedReq raw) {
    final ptr = inner.new_box_autoadd_phrase_to_seed_req_0();
    _api_fill_to_wire_phrase_to_seed_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_SchnorrFromSeedReq> api2wire_box_autoadd_schnorr_from_seed_req(SchnorrFromSeedReq raw) {
    final ptr = inner.new_box_autoadd_schnorr_from_seed_req_0();
    _api_fill_to_wire_schnorr_from_seed_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_SchnorrSignWithSeedReq> api2wire_box_autoadd_schnorr_sign_with_seed_req(SchnorrSignWithSeedReq raw) {
    final ptr = inner.new_box_autoadd_schnorr_sign_with_seed_req_0();
    _api_fill_to_wire_schnorr_sign_with_seed_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_SchnorrVerifyReq> api2wire_box_autoadd_schnorr_verify_req(SchnorrVerifyReq raw) {
    final ptr = inner.new_box_autoadd_schnorr_verify_req_0();
    _api_fill_to_wire_schnorr_verify_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_ScriptDeriveReq> api2wire_box_autoadd_script_derive_req(ScriptDeriveReq raw) {
    final ptr = inner.new_box_autoadd_script_derive_req_0();
    _api_fill_to_wire_script_derive_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_Secp256k1FromSeedReq> api2wire_box_autoadd_secp_256_k_1_from_seed_req(Secp256k1FromSeedReq raw) {
    final ptr = inner.new_box_autoadd_secp_256_k_1_from_seed_req_0();
    _api_fill_to_wire_secp_256_k_1_from_seed_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_Secp256k1RecoverReq> api2wire_box_autoadd_secp_256_k_1_recover_req(Secp256k1RecoverReq raw) {
    final ptr = inner.new_box_autoadd_secp_256_k_1_recover_req_0();
    _api_fill_to_wire_secp_256_k_1_recover_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_Secp256k1ShareSecretReq> api2wire_box_autoadd_secp_256_k_1_share_secret_req(Secp256k1ShareSecretReq raw) {
    final ptr = inner.new_box_autoadd_secp_256_k_1_share_secret_req_0();
    _api_fill_to_wire_secp_256_k_1_share_secret_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_Secp256k1SignWithSeedReq> api2wire_box_autoadd_secp_256_k_1_sign_with_seed_req(Secp256k1SignWithSeedReq raw) {
    final ptr = inner.new_box_autoadd_secp_256_k_1_sign_with_seed_req_0();
    _api_fill_to_wire_secp_256_k_1_sign_with_seed_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_Secp256k1VerifyReq> api2wire_box_autoadd_secp_256_k_1_verify_req(Secp256k1VerifyReq raw) {
    final ptr = inner.new_box_autoadd_secp_256_k_1_verify_req_0();
    _api_fill_to_wire_secp_256_k_1_verify_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_SeedToKeyReq> api2wire_box_autoadd_seed_to_key_req(SeedToKeyReq raw) {
    final ptr = inner.new_box_autoadd_seed_to_key_req_0();
    _api_fill_to_wire_seed_to_key_req(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<ffi.Uint8> api2wire_box_autoadd_u8(int raw) {
    return inner.new_box_autoadd_u8_0(api2wire_u8(raw));
  }

  @protected
  ffi.Pointer<ffi.Uint8> api2wire_opt_box_autoadd_u8(int? raw) {
    return raw == null ? ffi.nullptr : api2wire_box_autoadd_u8(raw);
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_opt_uint_8_list(Uint8List? raw) {
    return raw == null ? ffi.nullptr : api2wire_uint_8_list(raw);
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_uint_8_list(Uint8List raw) {
    final ans = inner.new_uint_8_list_0(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }
// Section: finalizer

// Section: api_fill_to_wire

  void _api_fill_to_wire_aes_decrypt_req(AesDecryptReq apiObj, wire_AesDecryptReq wireObj) {
    wireObj.key = api2wire_uint_8_list(apiObj.key);
    wireObj.iv = api2wire_uint_8_list(apiObj.iv);
    wireObj.cipher_text = api2wire_uint_8_list(apiObj.cipherText);
  }

  void _api_fill_to_wire_aes_encrypt_req(AesEncryptReq apiObj, wire_AesEncryptReq wireObj) {
    wireObj.key = api2wire_uint_8_list(apiObj.key);
    wireObj.iv = api2wire_uint_8_list(apiObj.iv);
    wireObj.message = api2wire_uint_8_list(apiObj.message);
  }

  void _api_fill_to_wire_bls_verify_req(BLSVerifyReq apiObj, wire_BLSVerifyReq wireObj) {
    wireObj.signature = api2wire_uint_8_list(apiObj.signature);
    wireObj.message = api2wire_uint_8_list(apiObj.message);
    wireObj.public_key = api2wire_uint_8_list(apiObj.publicKey);
  }

  void _api_fill_to_wire_box_autoadd_aes_decrypt_req(AesDecryptReq apiObj, ffi.Pointer<wire_AesDecryptReq> wireObj) {
    _api_fill_to_wire_aes_decrypt_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_aes_encrypt_req(AesEncryptReq apiObj, ffi.Pointer<wire_AesEncryptReq> wireObj) {
    _api_fill_to_wire_aes_encrypt_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_bls_verify_req(BLSVerifyReq apiObj, ffi.Pointer<wire_BLSVerifyReq> wireObj) {
    _api_fill_to_wire_bls_verify_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_ed_25519_from_seed_req(ED25519FromSeedReq apiObj, ffi.Pointer<wire_ED25519FromSeedReq> wireObj) {
    _api_fill_to_wire_ed_25519_from_seed_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_ed_25519_sign_req(ED25519SignReq apiObj, ffi.Pointer<wire_ED25519SignReq> wireObj) {
    _api_fill_to_wire_ed_25519_sign_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_ed_25519_verify_req(ED25519VerifyReq apiObj, ffi.Pointer<wire_ED25519VerifyReq> wireObj) {
    _api_fill_to_wire_ed_25519_verify_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_p_256_from_seed_req(P256FromSeedReq apiObj, ffi.Pointer<wire_P256FromSeedReq> wireObj) {
    _api_fill_to_wire_p_256_from_seed_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_p_256_share_secret_req(P256ShareSecretReq apiObj, ffi.Pointer<wire_P256ShareSecretReq> wireObj) {
    _api_fill_to_wire_p_256_share_secret_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_p_256_sign_with_seed_req(P256SignWithSeedReq apiObj, ffi.Pointer<wire_P256SignWithSeedReq> wireObj) {
    _api_fill_to_wire_p_256_sign_with_seed_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_p_256_verify_req(P256VerifyReq apiObj, ffi.Pointer<wire_P256VerifyReq> wireObj) {
    _api_fill_to_wire_p_256_verify_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_pbkdf_derive_req(PBKDFDeriveReq apiObj, ffi.Pointer<wire_PBKDFDeriveReq> wireObj) {
    _api_fill_to_wire_pbkdf_derive_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_phrase_to_seed_req(PhraseToSeedReq apiObj, ffi.Pointer<wire_PhraseToSeedReq> wireObj) {
    _api_fill_to_wire_phrase_to_seed_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_schnorr_from_seed_req(SchnorrFromSeedReq apiObj, ffi.Pointer<wire_SchnorrFromSeedReq> wireObj) {
    _api_fill_to_wire_schnorr_from_seed_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_schnorr_sign_with_seed_req(SchnorrSignWithSeedReq apiObj, ffi.Pointer<wire_SchnorrSignWithSeedReq> wireObj) {
    _api_fill_to_wire_schnorr_sign_with_seed_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_schnorr_verify_req(SchnorrVerifyReq apiObj, ffi.Pointer<wire_SchnorrVerifyReq> wireObj) {
    _api_fill_to_wire_schnorr_verify_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_script_derive_req(ScriptDeriveReq apiObj, ffi.Pointer<wire_ScriptDeriveReq> wireObj) {
    _api_fill_to_wire_script_derive_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_secp_256_k_1_from_seed_req(Secp256k1FromSeedReq apiObj, ffi.Pointer<wire_Secp256k1FromSeedReq> wireObj) {
    _api_fill_to_wire_secp_256_k_1_from_seed_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_secp_256_k_1_recover_req(Secp256k1RecoverReq apiObj, ffi.Pointer<wire_Secp256k1RecoverReq> wireObj) {
    _api_fill_to_wire_secp_256_k_1_recover_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_secp_256_k_1_share_secret_req(Secp256k1ShareSecretReq apiObj, ffi.Pointer<wire_Secp256k1ShareSecretReq> wireObj) {
    _api_fill_to_wire_secp_256_k_1_share_secret_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_secp_256_k_1_sign_with_seed_req(Secp256k1SignWithSeedReq apiObj, ffi.Pointer<wire_Secp256k1SignWithSeedReq> wireObj) {
    _api_fill_to_wire_secp_256_k_1_sign_with_seed_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_secp_256_k_1_verify_req(Secp256k1VerifyReq apiObj, ffi.Pointer<wire_Secp256k1VerifyReq> wireObj) {
    _api_fill_to_wire_secp_256_k_1_verify_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_box_autoadd_seed_to_key_req(SeedToKeyReq apiObj, ffi.Pointer<wire_SeedToKeyReq> wireObj) {
    _api_fill_to_wire_seed_to_key_req(apiObj, wireObj.ref);
  }

  void _api_fill_to_wire_ed_25519_from_seed_req(ED25519FromSeedReq apiObj, wire_ED25519FromSeedReq wireObj) {
    wireObj.seed = api2wire_uint_8_list(apiObj.seed);
  }

  void _api_fill_to_wire_ed_25519_sign_req(ED25519SignReq apiObj, wire_ED25519SignReq wireObj) {
    wireObj.seed = api2wire_uint_8_list(apiObj.seed);
    wireObj.message = api2wire_uint_8_list(apiObj.message);
  }

  void _api_fill_to_wire_ed_25519_verify_req(ED25519VerifyReq apiObj, wire_ED25519VerifyReq wireObj) {
    wireObj.sig = api2wire_uint_8_list(apiObj.sig);
    wireObj.message = api2wire_uint_8_list(apiObj.message);
    wireObj.pub_key = api2wire_uint_8_list(apiObj.pubKey);
  }

  void _api_fill_to_wire_p_256_from_seed_req(P256FromSeedReq apiObj, wire_P256FromSeedReq wireObj) {
    wireObj.seed = api2wire_uint_8_list(apiObj.seed);
  }

  void _api_fill_to_wire_p_256_share_secret_req(P256ShareSecretReq apiObj, wire_P256ShareSecretReq wireObj) {
    wireObj.seed = api2wire_uint_8_list(apiObj.seed);
    wireObj.public_key_raw_bytes = api2wire_uint_8_list(apiObj.publicKeyRawBytes);
  }

  void _api_fill_to_wire_p_256_sign_with_seed_req(P256SignWithSeedReq apiObj, wire_P256SignWithSeedReq wireObj) {
    wireObj.msg = api2wire_uint_8_list(apiObj.msg);
    wireObj.seed = api2wire_uint_8_list(apiObj.seed);
  }

  void _api_fill_to_wire_p_256_verify_req(P256VerifyReq apiObj, wire_P256VerifyReq wireObj) {
    wireObj.message_hash = api2wire_uint_8_list(apiObj.messageHash);
    wireObj.signature_bytes = api2wire_uint_8_list(apiObj.signatureBytes);
    wireObj.public_key_bytes = api2wire_uint_8_list(apiObj.publicKeyBytes);
  }

  void _api_fill_to_wire_pbkdf_derive_req(PBKDFDeriveReq apiObj, wire_PBKDFDeriveReq wireObj) {
    wireObj.password = api2wire_uint_8_list(apiObj.password);
    wireObj.salt = api2wire_uint_8_list(apiObj.salt);
    wireObj.c = api2wire_u32(apiObj.c);
  }

  void _api_fill_to_wire_phrase_to_seed_req(PhraseToSeedReq apiObj, wire_PhraseToSeedReq wireObj) {
    wireObj.phrase = api2wire_String(apiObj.phrase);
    wireObj.password = api2wire_String(apiObj.password);
  }

  void _api_fill_to_wire_schnorr_from_seed_req(SchnorrFromSeedReq apiObj, wire_SchnorrFromSeedReq wireObj) {
    wireObj.seed = api2wire_uint_8_list(apiObj.seed);
  }

  void _api_fill_to_wire_schnorr_sign_with_seed_req(SchnorrSignWithSeedReq apiObj, wire_SchnorrSignWithSeedReq wireObj) {
    wireObj.msg = api2wire_uint_8_list(apiObj.msg);
    wireObj.seed = api2wire_uint_8_list(apiObj.seed);
    wireObj.aux_rand = api2wire_opt_uint_8_list(apiObj.auxRand);
  }

  void _api_fill_to_wire_schnorr_verify_req(SchnorrVerifyReq apiObj, wire_SchnorrVerifyReq wireObj) {
    wireObj.message_hash = api2wire_uint_8_list(apiObj.messageHash);
    wireObj.signature_bytes = api2wire_uint_8_list(apiObj.signatureBytes);
    wireObj.public_key_bytes = api2wire_uint_8_list(apiObj.publicKeyBytes);
  }

  void _api_fill_to_wire_script_derive_req(ScriptDeriveReq apiObj, wire_ScriptDeriveReq wireObj) {
    wireObj.password = api2wire_uint_8_list(apiObj.password);
    wireObj.salt = api2wire_uint_8_list(apiObj.salt);
    wireObj.n = api2wire_u32(apiObj.n);
    wireObj.p = api2wire_u32(apiObj.p);
    wireObj.r = api2wire_u32(apiObj.r);
  }

  void _api_fill_to_wire_secp_256_k_1_from_seed_req(Secp256k1FromSeedReq apiObj, wire_Secp256k1FromSeedReq wireObj) {
    wireObj.seed = api2wire_uint_8_list(apiObj.seed);
  }

  void _api_fill_to_wire_secp_256_k_1_recover_req(Secp256k1RecoverReq apiObj, wire_Secp256k1RecoverReq wireObj) {
    wireObj.message_pre_hashed = api2wire_uint_8_list(apiObj.messagePreHashed);
    wireObj.signature_bytes = api2wire_uint_8_list(apiObj.signatureBytes);
    wireObj.chain_id = api2wire_opt_box_autoadd_u8(apiObj.chainId);
  }

  void _api_fill_to_wire_secp_256_k_1_share_secret_req(Secp256k1ShareSecretReq apiObj, wire_Secp256k1ShareSecretReq wireObj) {
    wireObj.seed = api2wire_uint_8_list(apiObj.seed);
    wireObj.public_key_raw_bytes = api2wire_uint_8_list(apiObj.publicKeyRawBytes);
  }

  void _api_fill_to_wire_secp_256_k_1_sign_with_seed_req(Secp256k1SignWithSeedReq apiObj, wire_Secp256k1SignWithSeedReq wireObj) {
    wireObj.msg = api2wire_uint_8_list(apiObj.msg);
    wireObj.seed = api2wire_uint_8_list(apiObj.seed);
  }

  void _api_fill_to_wire_secp_256_k_1_verify_req(Secp256k1VerifyReq apiObj, wire_Secp256k1VerifyReq wireObj) {
    wireObj.message_hash = api2wire_uint_8_list(apiObj.messageHash);
    wireObj.signature_bytes = api2wire_uint_8_list(apiObj.signatureBytes);
    wireObj.public_key_bytes = api2wire_uint_8_list(apiObj.publicKeyBytes);
  }

  void _api_fill_to_wire_seed_to_key_req(SeedToKeyReq apiObj, wire_SeedToKeyReq wireObj) {
    wireObj.seed = api2wire_uint_8_list(apiObj.seed);
    wireObj.path = api2wire_String(apiObj.path);
  }
}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class AgentDartWire implements FlutterRustBridgeWireBase {
  @internal
  late final dartApi = DartApiDl(init_frb_dart_api_dl);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  AgentDartWire(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  AgentDartWire.fromLookup(ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup) : _lookup = lookup;

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr = _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>('store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr.asFunction<void Function(DartPostCObjectFnType)>();

  Object get_dart_object(
    int ptr,
  ) {
    return _get_dart_object(
      ptr,
    );
  }

  late final _get_dart_objectPtr = _lookup<ffi.NativeFunction<ffi.Handle Function(ffi.UintPtr)>>('get_dart_object');
  late final _get_dart_object = _get_dart_objectPtr.asFunction<Object Function(int)>();

  void drop_dart_object(
    int ptr,
  ) {
    return _drop_dart_object(
      ptr,
    );
  }

  late final _drop_dart_objectPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>('drop_dart_object');
  late final _drop_dart_object = _drop_dart_objectPtr.asFunction<void Function(int)>();

  int new_dart_opaque(
    Object handle,
  ) {
    return _new_dart_opaque(
      handle,
    );
  }

  late final _new_dart_opaquePtr = _lookup<ffi.NativeFunction<ffi.UintPtr Function(ffi.Handle)>>('new_dart_opaque');
  late final _new_dart_opaque = _new_dart_opaquePtr.asFunction<int Function(Object)>();

  int init_frb_dart_api_dl(
    ffi.Pointer<ffi.Void> obj,
  ) {
    return _init_frb_dart_api_dl(
      obj,
    );
  }

  late final _init_frb_dart_api_dlPtr = _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>('init_frb_dart_api_dl');
  late final _init_frb_dart_api_dl = _init_frb_dart_api_dlPtr.asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  void wire_mnemonic_phrase_to_seed(
    int port_,
    ffi.Pointer<wire_PhraseToSeedReq> req,
  ) {
    return _wire_mnemonic_phrase_to_seed(
      port_,
      req,
    );
  }

  late final _wire_mnemonic_phrase_to_seedPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_PhraseToSeedReq>)>>('wire_mnemonic_phrase_to_seed');
  late final _wire_mnemonic_phrase_to_seed = _wire_mnemonic_phrase_to_seedPtr.asFunction<void Function(int, ffi.Pointer<wire_PhraseToSeedReq>)>();

  void wire_mnemonic_seed_to_key(
    int port_,
    ffi.Pointer<wire_SeedToKeyReq> req,
  ) {
    return _wire_mnemonic_seed_to_key(
      port_,
      req,
    );
  }

  late final _wire_mnemonic_seed_to_keyPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_SeedToKeyReq>)>>('wire_mnemonic_seed_to_key');
  late final _wire_mnemonic_seed_to_key = _wire_mnemonic_seed_to_keyPtr.asFunction<void Function(int, ffi.Pointer<wire_SeedToKeyReq>)>();

  void wire_bls_init(
    int port_,
  ) {
    return _wire_bls_init(
      port_,
    );
  }

  late final _wire_bls_initPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>('wire_bls_init');
  late final _wire_bls_init = _wire_bls_initPtr.asFunction<void Function(int)>();

  void wire_bls_verify(
    int port_,
    ffi.Pointer<wire_BLSVerifyReq> req,
  ) {
    return _wire_bls_verify(
      port_,
      req,
    );
  }

  late final _wire_bls_verifyPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_BLSVerifyReq>)>>('wire_bls_verify');
  late final _wire_bls_verify = _wire_bls_verifyPtr.asFunction<void Function(int, ffi.Pointer<wire_BLSVerifyReq>)>();

  void wire_ed25519_from_seed(
    int port_,
    ffi.Pointer<wire_ED25519FromSeedReq> req,
  ) {
    return _wire_ed25519_from_seed(
      port_,
      req,
    );
  }

  late final _wire_ed25519_from_seedPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_ED25519FromSeedReq>)>>('wire_ed25519_from_seed');
  late final _wire_ed25519_from_seed = _wire_ed25519_from_seedPtr.asFunction<void Function(int, ffi.Pointer<wire_ED25519FromSeedReq>)>();

  void wire_ed25519_sign(
    int port_,
    ffi.Pointer<wire_ED25519SignReq> req,
  ) {
    return _wire_ed25519_sign(
      port_,
      req,
    );
  }

  late final _wire_ed25519_signPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_ED25519SignReq>)>>('wire_ed25519_sign');
  late final _wire_ed25519_sign = _wire_ed25519_signPtr.asFunction<void Function(int, ffi.Pointer<wire_ED25519SignReq>)>();

  void wire_ed25519_verify(
    int port_,
    ffi.Pointer<wire_ED25519VerifyReq> req,
  ) {
    return _wire_ed25519_verify(
      port_,
      req,
    );
  }

  late final _wire_ed25519_verifyPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_ED25519VerifyReq>)>>('wire_ed25519_verify');
  late final _wire_ed25519_verify = _wire_ed25519_verifyPtr.asFunction<void Function(int, ffi.Pointer<wire_ED25519VerifyReq>)>();

  void wire_secp256k1_from_seed(
    int port_,
    ffi.Pointer<wire_Secp256k1FromSeedReq> req,
  ) {
    return _wire_secp256k1_from_seed(
      port_,
      req,
    );
  }

  late final _wire_secp256k1_from_seedPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_Secp256k1FromSeedReq>)>>('wire_secp256k1_from_seed');
  late final _wire_secp256k1_from_seed = _wire_secp256k1_from_seedPtr.asFunction<void Function(int, ffi.Pointer<wire_Secp256k1FromSeedReq>)>();

  void wire_secp256k1_sign(
    int port_,
    ffi.Pointer<wire_Secp256k1SignWithSeedReq> req,
  ) {
    return _wire_secp256k1_sign(
      port_,
      req,
    );
  }

  late final _wire_secp256k1_signPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_Secp256k1SignWithSeedReq>)>>('wire_secp256k1_sign');
  late final _wire_secp256k1_sign = _wire_secp256k1_signPtr.asFunction<void Function(int, ffi.Pointer<wire_Secp256k1SignWithSeedReq>)>();

  void wire_secp256k1_sign_recoverable(
    int port_,
    ffi.Pointer<wire_Secp256k1SignWithSeedReq> req,
  ) {
    return _wire_secp256k1_sign_recoverable(
      port_,
      req,
    );
  }

  late final _wire_secp256k1_sign_recoverablePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_Secp256k1SignWithSeedReq>)>>('wire_secp256k1_sign_recoverable');
  late final _wire_secp256k1_sign_recoverable = _wire_secp256k1_sign_recoverablePtr.asFunction<void Function(int, ffi.Pointer<wire_Secp256k1SignWithSeedReq>)>();

  void wire_secp256k1_verify(
    int port_,
    ffi.Pointer<wire_Secp256k1VerifyReq> req,
  ) {
    return _wire_secp256k1_verify(
      port_,
      req,
    );
  }

  late final _wire_secp256k1_verifyPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_Secp256k1VerifyReq>)>>('wire_secp256k1_verify');
  late final _wire_secp256k1_verify = _wire_secp256k1_verifyPtr.asFunction<void Function(int, ffi.Pointer<wire_Secp256k1VerifyReq>)>();

  void wire_secp256k1_get_shared_secret(
    int port_,
    ffi.Pointer<wire_Secp256k1ShareSecretReq> req,
  ) {
    return _wire_secp256k1_get_shared_secret(
      port_,
      req,
    );
  }

  late final _wire_secp256k1_get_shared_secretPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_Secp256k1ShareSecretReq>)>>('wire_secp256k1_get_shared_secret');
  late final _wire_secp256k1_get_shared_secret = _wire_secp256k1_get_shared_secretPtr.asFunction<void Function(int, ffi.Pointer<wire_Secp256k1ShareSecretReq>)>();

  void wire_secp256k1_recover(
    int port_,
    ffi.Pointer<wire_Secp256k1RecoverReq> req,
  ) {
    return _wire_secp256k1_recover(
      port_,
      req,
    );
  }

  late final _wire_secp256k1_recoverPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_Secp256k1RecoverReq>)>>('wire_secp256k1_recover');
  late final _wire_secp256k1_recover = _wire_secp256k1_recoverPtr.asFunction<void Function(int, ffi.Pointer<wire_Secp256k1RecoverReq>)>();

  void wire_p256_from_seed(
    int port_,
    ffi.Pointer<wire_P256FromSeedReq> req,
  ) {
    return _wire_p256_from_seed(
      port_,
      req,
    );
  }

  late final _wire_p256_from_seedPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_P256FromSeedReq>)>>('wire_p256_from_seed');
  late final _wire_p256_from_seed = _wire_p256_from_seedPtr.asFunction<void Function(int, ffi.Pointer<wire_P256FromSeedReq>)>();

  void wire_p256_sign(
    int port_,
    ffi.Pointer<wire_P256SignWithSeedReq> req,
  ) {
    return _wire_p256_sign(
      port_,
      req,
    );
  }

  late final _wire_p256_signPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_P256SignWithSeedReq>)>>('wire_p256_sign');
  late final _wire_p256_sign = _wire_p256_signPtr.asFunction<void Function(int, ffi.Pointer<wire_P256SignWithSeedReq>)>();

  void wire_p256_verify(
    int port_,
    ffi.Pointer<wire_P256VerifyReq> req,
  ) {
    return _wire_p256_verify(
      port_,
      req,
    );
  }

  late final _wire_p256_verifyPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_P256VerifyReq>)>>('wire_p256_verify');
  late final _wire_p256_verify = _wire_p256_verifyPtr.asFunction<void Function(int, ffi.Pointer<wire_P256VerifyReq>)>();

  void wire_p256_get_shared_secret(
    int port_,
    ffi.Pointer<wire_P256ShareSecretReq> req,
  ) {
    return _wire_p256_get_shared_secret(
      port_,
      req,
    );
  }

  late final _wire_p256_get_shared_secretPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_P256ShareSecretReq>)>>('wire_p256_get_shared_secret');
  late final _wire_p256_get_shared_secret = _wire_p256_get_shared_secretPtr.asFunction<void Function(int, ffi.Pointer<wire_P256ShareSecretReq>)>();

  void wire_schnorr_from_seed(
    int port_,
    ffi.Pointer<wire_SchnorrFromSeedReq> req,
  ) {
    return _wire_schnorr_from_seed(
      port_,
      req,
    );
  }

  late final _wire_schnorr_from_seedPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_SchnorrFromSeedReq>)>>('wire_schnorr_from_seed');
  late final _wire_schnorr_from_seed = _wire_schnorr_from_seedPtr.asFunction<void Function(int, ffi.Pointer<wire_SchnorrFromSeedReq>)>();

  void wire_schnorr_sign(
    int port_,
    ffi.Pointer<wire_SchnorrSignWithSeedReq> req,
  ) {
    return _wire_schnorr_sign(
      port_,
      req,
    );
  }

  late final _wire_schnorr_signPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_SchnorrSignWithSeedReq>)>>('wire_schnorr_sign');
  late final _wire_schnorr_sign = _wire_schnorr_signPtr.asFunction<void Function(int, ffi.Pointer<wire_SchnorrSignWithSeedReq>)>();

  void wire_schnorr_verify(
    int port_,
    ffi.Pointer<wire_SchnorrVerifyReq> req,
  ) {
    return _wire_schnorr_verify(
      port_,
      req,
    );
  }

  late final _wire_schnorr_verifyPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_SchnorrVerifyReq>)>>('wire_schnorr_verify');
  late final _wire_schnorr_verify = _wire_schnorr_verifyPtr.asFunction<void Function(int, ffi.Pointer<wire_SchnorrVerifyReq>)>();

  void wire_aes_128_ctr_encrypt(
    int port_,
    ffi.Pointer<wire_AesEncryptReq> req,
  ) {
    return _wire_aes_128_ctr_encrypt(
      port_,
      req,
    );
  }

  late final _wire_aes_128_ctr_encryptPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_AesEncryptReq>)>>('wire_aes_128_ctr_encrypt');
  late final _wire_aes_128_ctr_encrypt = _wire_aes_128_ctr_encryptPtr.asFunction<void Function(int, ffi.Pointer<wire_AesEncryptReq>)>();

  void wire_aes_128_ctr_decrypt(
    int port_,
    ffi.Pointer<wire_AesDecryptReq> req,
  ) {
    return _wire_aes_128_ctr_decrypt(
      port_,
      req,
    );
  }

  late final _wire_aes_128_ctr_decryptPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_AesDecryptReq>)>>('wire_aes_128_ctr_decrypt');
  late final _wire_aes_128_ctr_decrypt = _wire_aes_128_ctr_decryptPtr.asFunction<void Function(int, ffi.Pointer<wire_AesDecryptReq>)>();

  void wire_aes_256_cbc_encrypt(
    int port_,
    ffi.Pointer<wire_AesEncryptReq> req,
  ) {
    return _wire_aes_256_cbc_encrypt(
      port_,
      req,
    );
  }

  late final _wire_aes_256_cbc_encryptPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_AesEncryptReq>)>>('wire_aes_256_cbc_encrypt');
  late final _wire_aes_256_cbc_encrypt = _wire_aes_256_cbc_encryptPtr.asFunction<void Function(int, ffi.Pointer<wire_AesEncryptReq>)>();

  void wire_aes_256_cbc_decrypt(
    int port_,
    ffi.Pointer<wire_AesDecryptReq> req,
  ) {
    return _wire_aes_256_cbc_decrypt(
      port_,
      req,
    );
  }

  late final _wire_aes_256_cbc_decryptPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_AesDecryptReq>)>>('wire_aes_256_cbc_decrypt');
  late final _wire_aes_256_cbc_decrypt = _wire_aes_256_cbc_decryptPtr.asFunction<void Function(int, ffi.Pointer<wire_AesDecryptReq>)>();

  void wire_aes_256_gcm_encrypt(
    int port_,
    ffi.Pointer<wire_AesEncryptReq> req,
  ) {
    return _wire_aes_256_gcm_encrypt(
      port_,
      req,
    );
  }

  late final _wire_aes_256_gcm_encryptPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_AesEncryptReq>)>>('wire_aes_256_gcm_encrypt');
  late final _wire_aes_256_gcm_encrypt = _wire_aes_256_gcm_encryptPtr.asFunction<void Function(int, ffi.Pointer<wire_AesEncryptReq>)>();

  void wire_aes_256_gcm_decrypt(
    int port_,
    ffi.Pointer<wire_AesDecryptReq> req,
  ) {
    return _wire_aes_256_gcm_decrypt(
      port_,
      req,
    );
  }

  late final _wire_aes_256_gcm_decryptPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_AesDecryptReq>)>>('wire_aes_256_gcm_decrypt');
  late final _wire_aes_256_gcm_decrypt = _wire_aes_256_gcm_decryptPtr.asFunction<void Function(int, ffi.Pointer<wire_AesDecryptReq>)>();

  void wire_pbkdf2_derive_key(
    int port_,
    ffi.Pointer<wire_PBKDFDeriveReq> req,
  ) {
    return _wire_pbkdf2_derive_key(
      port_,
      req,
    );
  }

  late final _wire_pbkdf2_derive_keyPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_PBKDFDeriveReq>)>>('wire_pbkdf2_derive_key');
  late final _wire_pbkdf2_derive_key = _wire_pbkdf2_derive_keyPtr.asFunction<void Function(int, ffi.Pointer<wire_PBKDFDeriveReq>)>();

  void wire_scrypt_derive_key(
    int port_,
    ffi.Pointer<wire_ScriptDeriveReq> req,
  ) {
    return _wire_scrypt_derive_key(
      port_,
      req,
    );
  }

  late final _wire_scrypt_derive_keyPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_ScriptDeriveReq>)>>('wire_scrypt_derive_key');
  late final _wire_scrypt_derive_key = _wire_scrypt_derive_keyPtr.asFunction<void Function(int, ffi.Pointer<wire_ScriptDeriveReq>)>();

  ffi.Pointer<wire_AesDecryptReq> new_box_autoadd_aes_decrypt_req_0() {
    return _new_box_autoadd_aes_decrypt_req_0();
  }

  late final _new_box_autoadd_aes_decrypt_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_AesDecryptReq> Function()>>('new_box_autoadd_aes_decrypt_req_0');
  late final _new_box_autoadd_aes_decrypt_req_0 = _new_box_autoadd_aes_decrypt_req_0Ptr.asFunction<ffi.Pointer<wire_AesDecryptReq> Function()>();

  ffi.Pointer<wire_AesEncryptReq> new_box_autoadd_aes_encrypt_req_0() {
    return _new_box_autoadd_aes_encrypt_req_0();
  }

  late final _new_box_autoadd_aes_encrypt_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_AesEncryptReq> Function()>>('new_box_autoadd_aes_encrypt_req_0');
  late final _new_box_autoadd_aes_encrypt_req_0 = _new_box_autoadd_aes_encrypt_req_0Ptr.asFunction<ffi.Pointer<wire_AesEncryptReq> Function()>();

  ffi.Pointer<wire_BLSVerifyReq> new_box_autoadd_bls_verify_req_0() {
    return _new_box_autoadd_bls_verify_req_0();
  }

  late final _new_box_autoadd_bls_verify_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_BLSVerifyReq> Function()>>('new_box_autoadd_bls_verify_req_0');
  late final _new_box_autoadd_bls_verify_req_0 = _new_box_autoadd_bls_verify_req_0Ptr.asFunction<ffi.Pointer<wire_BLSVerifyReq> Function()>();

  ffi.Pointer<wire_ED25519FromSeedReq> new_box_autoadd_ed_25519_from_seed_req_0() {
    return _new_box_autoadd_ed_25519_from_seed_req_0();
  }

  late final _new_box_autoadd_ed_25519_from_seed_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_ED25519FromSeedReq> Function()>>('new_box_autoadd_ed_25519_from_seed_req_0');
  late final _new_box_autoadd_ed_25519_from_seed_req_0 = _new_box_autoadd_ed_25519_from_seed_req_0Ptr.asFunction<ffi.Pointer<wire_ED25519FromSeedReq> Function()>();

  ffi.Pointer<wire_ED25519SignReq> new_box_autoadd_ed_25519_sign_req_0() {
    return _new_box_autoadd_ed_25519_sign_req_0();
  }

  late final _new_box_autoadd_ed_25519_sign_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_ED25519SignReq> Function()>>('new_box_autoadd_ed_25519_sign_req_0');
  late final _new_box_autoadd_ed_25519_sign_req_0 = _new_box_autoadd_ed_25519_sign_req_0Ptr.asFunction<ffi.Pointer<wire_ED25519SignReq> Function()>();

  ffi.Pointer<wire_ED25519VerifyReq> new_box_autoadd_ed_25519_verify_req_0() {
    return _new_box_autoadd_ed_25519_verify_req_0();
  }

  late final _new_box_autoadd_ed_25519_verify_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_ED25519VerifyReq> Function()>>('new_box_autoadd_ed_25519_verify_req_0');
  late final _new_box_autoadd_ed_25519_verify_req_0 = _new_box_autoadd_ed_25519_verify_req_0Ptr.asFunction<ffi.Pointer<wire_ED25519VerifyReq> Function()>();

  ffi.Pointer<wire_P256FromSeedReq> new_box_autoadd_p_256_from_seed_req_0() {
    return _new_box_autoadd_p_256_from_seed_req_0();
  }

  late final _new_box_autoadd_p_256_from_seed_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_P256FromSeedReq> Function()>>('new_box_autoadd_p_256_from_seed_req_0');
  late final _new_box_autoadd_p_256_from_seed_req_0 = _new_box_autoadd_p_256_from_seed_req_0Ptr.asFunction<ffi.Pointer<wire_P256FromSeedReq> Function()>();

  ffi.Pointer<wire_P256ShareSecretReq> new_box_autoadd_p_256_share_secret_req_0() {
    return _new_box_autoadd_p_256_share_secret_req_0();
  }

  late final _new_box_autoadd_p_256_share_secret_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_P256ShareSecretReq> Function()>>('new_box_autoadd_p_256_share_secret_req_0');
  late final _new_box_autoadd_p_256_share_secret_req_0 = _new_box_autoadd_p_256_share_secret_req_0Ptr.asFunction<ffi.Pointer<wire_P256ShareSecretReq> Function()>();

  ffi.Pointer<wire_P256SignWithSeedReq> new_box_autoadd_p_256_sign_with_seed_req_0() {
    return _new_box_autoadd_p_256_sign_with_seed_req_0();
  }

  late final _new_box_autoadd_p_256_sign_with_seed_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_P256SignWithSeedReq> Function()>>('new_box_autoadd_p_256_sign_with_seed_req_0');
  late final _new_box_autoadd_p_256_sign_with_seed_req_0 = _new_box_autoadd_p_256_sign_with_seed_req_0Ptr.asFunction<ffi.Pointer<wire_P256SignWithSeedReq> Function()>();

  ffi.Pointer<wire_P256VerifyReq> new_box_autoadd_p_256_verify_req_0() {
    return _new_box_autoadd_p_256_verify_req_0();
  }

  late final _new_box_autoadd_p_256_verify_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_P256VerifyReq> Function()>>('new_box_autoadd_p_256_verify_req_0');
  late final _new_box_autoadd_p_256_verify_req_0 = _new_box_autoadd_p_256_verify_req_0Ptr.asFunction<ffi.Pointer<wire_P256VerifyReq> Function()>();

  ffi.Pointer<wire_PBKDFDeriveReq> new_box_autoadd_pbkdf_derive_req_0() {
    return _new_box_autoadd_pbkdf_derive_req_0();
  }

  late final _new_box_autoadd_pbkdf_derive_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_PBKDFDeriveReq> Function()>>('new_box_autoadd_pbkdf_derive_req_0');
  late final _new_box_autoadd_pbkdf_derive_req_0 = _new_box_autoadd_pbkdf_derive_req_0Ptr.asFunction<ffi.Pointer<wire_PBKDFDeriveReq> Function()>();

  ffi.Pointer<wire_PhraseToSeedReq> new_box_autoadd_phrase_to_seed_req_0() {
    return _new_box_autoadd_phrase_to_seed_req_0();
  }

  late final _new_box_autoadd_phrase_to_seed_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_PhraseToSeedReq> Function()>>('new_box_autoadd_phrase_to_seed_req_0');
  late final _new_box_autoadd_phrase_to_seed_req_0 = _new_box_autoadd_phrase_to_seed_req_0Ptr.asFunction<ffi.Pointer<wire_PhraseToSeedReq> Function()>();

  ffi.Pointer<wire_SchnorrFromSeedReq> new_box_autoadd_schnorr_from_seed_req_0() {
    return _new_box_autoadd_schnorr_from_seed_req_0();
  }

  late final _new_box_autoadd_schnorr_from_seed_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_SchnorrFromSeedReq> Function()>>('new_box_autoadd_schnorr_from_seed_req_0');
  late final _new_box_autoadd_schnorr_from_seed_req_0 = _new_box_autoadd_schnorr_from_seed_req_0Ptr.asFunction<ffi.Pointer<wire_SchnorrFromSeedReq> Function()>();

  ffi.Pointer<wire_SchnorrSignWithSeedReq> new_box_autoadd_schnorr_sign_with_seed_req_0() {
    return _new_box_autoadd_schnorr_sign_with_seed_req_0();
  }

  late final _new_box_autoadd_schnorr_sign_with_seed_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_SchnorrSignWithSeedReq> Function()>>('new_box_autoadd_schnorr_sign_with_seed_req_0');
  late final _new_box_autoadd_schnorr_sign_with_seed_req_0 = _new_box_autoadd_schnorr_sign_with_seed_req_0Ptr.asFunction<ffi.Pointer<wire_SchnorrSignWithSeedReq> Function()>();

  ffi.Pointer<wire_SchnorrVerifyReq> new_box_autoadd_schnorr_verify_req_0() {
    return _new_box_autoadd_schnorr_verify_req_0();
  }

  late final _new_box_autoadd_schnorr_verify_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_SchnorrVerifyReq> Function()>>('new_box_autoadd_schnorr_verify_req_0');
  late final _new_box_autoadd_schnorr_verify_req_0 = _new_box_autoadd_schnorr_verify_req_0Ptr.asFunction<ffi.Pointer<wire_SchnorrVerifyReq> Function()>();

  ffi.Pointer<wire_ScriptDeriveReq> new_box_autoadd_script_derive_req_0() {
    return _new_box_autoadd_script_derive_req_0();
  }

  late final _new_box_autoadd_script_derive_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_ScriptDeriveReq> Function()>>('new_box_autoadd_script_derive_req_0');
  late final _new_box_autoadd_script_derive_req_0 = _new_box_autoadd_script_derive_req_0Ptr.asFunction<ffi.Pointer<wire_ScriptDeriveReq> Function()>();

  ffi.Pointer<wire_Secp256k1FromSeedReq> new_box_autoadd_secp_256_k_1_from_seed_req_0() {
    return _new_box_autoadd_secp_256_k_1_from_seed_req_0();
  }

  late final _new_box_autoadd_secp_256_k_1_from_seed_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_Secp256k1FromSeedReq> Function()>>('new_box_autoadd_secp_256_k_1_from_seed_req_0');
  late final _new_box_autoadd_secp_256_k_1_from_seed_req_0 = _new_box_autoadd_secp_256_k_1_from_seed_req_0Ptr.asFunction<ffi.Pointer<wire_Secp256k1FromSeedReq> Function()>();

  ffi.Pointer<wire_Secp256k1RecoverReq> new_box_autoadd_secp_256_k_1_recover_req_0() {
    return _new_box_autoadd_secp_256_k_1_recover_req_0();
  }

  late final _new_box_autoadd_secp_256_k_1_recover_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_Secp256k1RecoverReq> Function()>>('new_box_autoadd_secp_256_k_1_recover_req_0');
  late final _new_box_autoadd_secp_256_k_1_recover_req_0 = _new_box_autoadd_secp_256_k_1_recover_req_0Ptr.asFunction<ffi.Pointer<wire_Secp256k1RecoverReq> Function()>();

  ffi.Pointer<wire_Secp256k1ShareSecretReq> new_box_autoadd_secp_256_k_1_share_secret_req_0() {
    return _new_box_autoadd_secp_256_k_1_share_secret_req_0();
  }

  late final _new_box_autoadd_secp_256_k_1_share_secret_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_Secp256k1ShareSecretReq> Function()>>('new_box_autoadd_secp_256_k_1_share_secret_req_0');
  late final _new_box_autoadd_secp_256_k_1_share_secret_req_0 = _new_box_autoadd_secp_256_k_1_share_secret_req_0Ptr.asFunction<ffi.Pointer<wire_Secp256k1ShareSecretReq> Function()>();

  ffi.Pointer<wire_Secp256k1SignWithSeedReq> new_box_autoadd_secp_256_k_1_sign_with_seed_req_0() {
    return _new_box_autoadd_secp_256_k_1_sign_with_seed_req_0();
  }

  late final _new_box_autoadd_secp_256_k_1_sign_with_seed_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_Secp256k1SignWithSeedReq> Function()>>('new_box_autoadd_secp_256_k_1_sign_with_seed_req_0');
  late final _new_box_autoadd_secp_256_k_1_sign_with_seed_req_0 = _new_box_autoadd_secp_256_k_1_sign_with_seed_req_0Ptr.asFunction<ffi.Pointer<wire_Secp256k1SignWithSeedReq> Function()>();

  ffi.Pointer<wire_Secp256k1VerifyReq> new_box_autoadd_secp_256_k_1_verify_req_0() {
    return _new_box_autoadd_secp_256_k_1_verify_req_0();
  }

  late final _new_box_autoadd_secp_256_k_1_verify_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_Secp256k1VerifyReq> Function()>>('new_box_autoadd_secp_256_k_1_verify_req_0');
  late final _new_box_autoadd_secp_256_k_1_verify_req_0 = _new_box_autoadd_secp_256_k_1_verify_req_0Ptr.asFunction<ffi.Pointer<wire_Secp256k1VerifyReq> Function()>();

  ffi.Pointer<wire_SeedToKeyReq> new_box_autoadd_seed_to_key_req_0() {
    return _new_box_autoadd_seed_to_key_req_0();
  }

  late final _new_box_autoadd_seed_to_key_req_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_SeedToKeyReq> Function()>>('new_box_autoadd_seed_to_key_req_0');
  late final _new_box_autoadd_seed_to_key_req_0 = _new_box_autoadd_seed_to_key_req_0Ptr.asFunction<ffi.Pointer<wire_SeedToKeyReq> Function()>();

  ffi.Pointer<ffi.Uint8> new_box_autoadd_u8_0(
    int value,
  ) {
    return _new_box_autoadd_u8_0(
      value,
    );
  }

  late final _new_box_autoadd_u8_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Uint8> Function(ffi.Uint8)>>('new_box_autoadd_u8_0');
  late final _new_box_autoadd_u8_0 = _new_box_autoadd_u8_0Ptr.asFunction<ffi.Pointer<ffi.Uint8> Function(int)>();

  ffi.Pointer<wire_uint_8_list> new_uint_8_list_0(
    int len,
  ) {
    return _new_uint_8_list_0(
      len,
    );
  }

  late final _new_uint_8_list_0Ptr = _lookup<ffi.NativeFunction<ffi.Pointer<wire_uint_8_list> Function(ffi.Int32)>>('new_uint_8_list_0');
  late final _new_uint_8_list_0 = _new_uint_8_list_0Ptr.asFunction<ffi.Pointer<wire_uint_8_list> Function(int)>();

  void free_WireSyncReturn(
    WireSyncReturn ptr,
  ) {
    return _free_WireSyncReturn(
      ptr,
    );
  }

  late final _free_WireSyncReturnPtr = _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturn)>>('free_WireSyncReturn');
  late final _free_WireSyncReturn = _free_WireSyncReturnPtr.asFunction<void Function(WireSyncReturn)>();
}

class _Dart_Handle extends ffi.Opaque {}

class wire_uint_8_list extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

class wire_PhraseToSeedReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> phrase;

  external ffi.Pointer<wire_uint_8_list> password;
}

class wire_SeedToKeyReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> seed;

  external ffi.Pointer<wire_uint_8_list> path;
}

class wire_BLSVerifyReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> signature;

  external ffi.Pointer<wire_uint_8_list> message;

  external ffi.Pointer<wire_uint_8_list> public_key;
}

class wire_ED25519FromSeedReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> seed;
}

class wire_ED25519SignReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> seed;

  external ffi.Pointer<wire_uint_8_list> message;
}

class wire_ED25519VerifyReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> sig;

  external ffi.Pointer<wire_uint_8_list> message;

  external ffi.Pointer<wire_uint_8_list> pub_key;
}

class wire_Secp256k1FromSeedReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> seed;
}

class wire_Secp256k1SignWithSeedReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> msg;

  external ffi.Pointer<wire_uint_8_list> seed;
}

class wire_Secp256k1VerifyReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> message_hash;

  external ffi.Pointer<wire_uint_8_list> signature_bytes;

  external ffi.Pointer<wire_uint_8_list> public_key_bytes;
}

class wire_Secp256k1ShareSecretReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> seed;

  external ffi.Pointer<wire_uint_8_list> public_key_raw_bytes;
}

class wire_Secp256k1RecoverReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> message_pre_hashed;

  external ffi.Pointer<wire_uint_8_list> signature_bytes;

  external ffi.Pointer<ffi.Uint8> chain_id;
}

class wire_P256FromSeedReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> seed;
}

class wire_P256SignWithSeedReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> msg;

  external ffi.Pointer<wire_uint_8_list> seed;
}

class wire_P256VerifyReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> message_hash;

  external ffi.Pointer<wire_uint_8_list> signature_bytes;

  external ffi.Pointer<wire_uint_8_list> public_key_bytes;
}

class wire_P256ShareSecretReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> seed;

  external ffi.Pointer<wire_uint_8_list> public_key_raw_bytes;
}

class wire_SchnorrFromSeedReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> seed;
}

class wire_SchnorrSignWithSeedReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> msg;

  external ffi.Pointer<wire_uint_8_list> seed;

  external ffi.Pointer<wire_uint_8_list> aux_rand;
}

class wire_SchnorrVerifyReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> message_hash;

  external ffi.Pointer<wire_uint_8_list> signature_bytes;

  external ffi.Pointer<wire_uint_8_list> public_key_bytes;
}

class wire_AesEncryptReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> key;

  external ffi.Pointer<wire_uint_8_list> iv;

  external ffi.Pointer<wire_uint_8_list> message;
}

class wire_AesDecryptReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> key;

  external ffi.Pointer<wire_uint_8_list> iv;

  external ffi.Pointer<wire_uint_8_list> cipher_text;
}

class wire_PBKDFDeriveReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> password;

  external ffi.Pointer<wire_uint_8_list> salt;

  @ffi.Uint32()
  external int c;
}

class wire_ScriptDeriveReq extends ffi.Struct {
  external ffi.Pointer<wire_uint_8_list> password;

  external ffi.Pointer<wire_uint_8_list> salt;

  @ffi.Uint32()
  external int n;

  @ffi.Uint32()
  external int p;

  @ffi.Uint32()
  external int r;
}

typedef DartPostCObjectFnType = ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(DartPort, ffi.Pointer<ffi.Void>)>>;
typedef DartPort = ffi.Int64;

const int ECB = 0;

const int CBC = 1;

const int CFB1 = 2;

const int CFB2 = 3;

const int CFB4 = 5;

const int OFB1 = 14;

const int OFB2 = 15;

const int OFB4 = 17;

const int OFB8 = 21;

const int OFB16 = 29;

const int CTR1 = 30;

const int CTR2 = 31;

const int CTR4 = 33;

const int CTR8 = 37;

const int CTR16 = 45;

const int CHUNK = 64;

const int MODBYTES = 48;

const int BASEBITS = 58;

const int NLEN = 7;

const int DNLEN = 14;

const int HBITS = 29;

const int BIGBITS = 384;

const int BLS_OK = 0;

const int BLS_FAIL = -1;

const int WEIERSTRASS = 0;

const int EDWARDS = 1;

const int MONTGOMERY = 2;

const int NOT = 0;

const int BN = 1;

const int BLS12 = 2;

const int BLS24 = 3;

const int BLS48 = 4;

const int D_TYPE = 0;

const int M_TYPE = 1;

const int POSITIVEX = 0;

const int NEGATIVEX = 1;

const int CURVETYPE = 0;

const int CURVE_A = 0;

const int CURVE_PAIRING_TYPE = 2;

const int SEXTIC_TWIST = 1;

const int SIGN_OF_X = 1;

const int ATE_BITS = 65;

const int G2_TABLE = 69;

const int HTC_ISO = 11;

const int HTC_ISO_G2 = 3;

const int ALLOW_ALT_COMPRESS = 1;

const int HASH_TYPE = 32;

const int AESKEY = 16;

const int NOT_SPECIAL = 0;

const int PSEUDO_MERSENNE = 1;

const int MONTGOMERY_FRIENDLY = 2;

const int GENERALISED_MERSENNE = 3;

const int NEGATOWER = 0;

const int POSITOWER = 1;

const int MODBITS = 381;

const int PM1D2 = 1;

const int RIADZ = 11;

const int RIADZG2A = -2;

const int RIADZG2B = -1;

const int MODTYPE = 0;

const int QNRI = 0;

const int TOWER = 0;

const int FEXCESS = 33554431;

const int BIG_ENDIAN_SIGN = 0;

const int ZERO = 0;

const int ONE = 1;

const int SPARSEST = 2;

const int SPARSER = 3;

const int SPARSE = 4;

const int DENSE = 5;

const int BAD_PARAMS = -11;

const int INVALID_POINT = -14;

const int WRONG_ORDER = -18;

const int BAD_PIN = -19;

const int SHA256 = 32;

const int SHA384 = 48;

const int SHA512 = 64;

const int MAXPIN = 10000;

const int PBLEN = 14;

const int CURVE_COF_I = 0;

const int CURVE_B_I = 4;

const int USE_GLV = 1;

const int USE_GS_G2 = 1;

const int USE_GS_GT = 1;

const int GT_STRONG = 0;

const int MC_SHA2 = 2;

const int MC_SHA3 = 3;

const int HASH224 = 28;

const int HASH256 = 32;

const int HASH384 = 48;

const int HASH512 = 64;

const int SHAKE128 = 16;

const int SHAKE256 = 32;

const int KEY_LENGTH = 32;

const int KEY_LENGTH_AES = 16;

const int BMASK = 2147483647;

const int HMASK = 536870911;

const int MCONST = 140737475470229501;
