name: Runnable (stable)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Analyze on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          cache: true
      - uses: bluefireteam/melos-action@v3
      - name: Replace symlinks
        run: ./scripts/replace_symlinks_before_publish.sh
      - run: cargo build --package=agent_dart
      - run: cd packages/agent_dart_base && dart test ./test/agent_dart_base_test.dart
      - name: Publish dry run
        run: melos run publish-dry-run
        if: ${{ github.repository == 'AstroxNetwork/agent_dart' && matrix.os == 'ubuntu-latest' }}
      - name: Build example
        working-directory: packages/agent_dart/example
        run: |
          if [[ ${{ matrix.os }} == 'macos-latest' ]]; then
            flutter build ios --debug --no-codesign
          elif [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
            flutter build apk --debug
          else
            echo "Well, nothing."
          fi
